Update JenkinsfileV1

diff --git a/JenkinsfileV1 b/JenkinsfileV1
--- a/JenkinsfileV1
+++ b/JenkinsfileV1
@@ -124,26 +124,26 @@ pipeline {
             }
         }
 
-        stage('Retry / Timeout Demo (tool-free)') {
-            steps {
-                script {
-                    timeout(time: 2, unit: 'MINUTES') {
-                        retry(2) {
-                            echo "Simulating a flaky operation..."
-                            sh '''
-                              set -eu
-                              # 50% chance to fail once
-                              if [ $((RANDOM % 2)) -eq 0 ]; then
-                                echo "Simulated failure"; exit 1
-                              else
-                                echo "Simulated success"
-                              fi
-                            '''
-                        }
-                    }
-                }
-            }
-        }
+        // stage('Retry / Timeout Demo (tool-free)') {
+        //     steps {
+        //         script {
+        //             timeout(time: 2, unit: 'MINUTES') {
+        //                 retry(2) {
+        //                     echo "Simulating a flaky operation..."
+        //                     sh '''
+        //                       set -eu
+        //                       # 50% chance to fail once
+        //                       if [ $((RANDOM % 2)) -eq 0 ]; then
+        //                         echo "Simulated failure"; exit 1
+        //                       else
+        //                         echo "Simulated success"
+        //                       fi
+        //                     '''
+        //                 }
+        //             }
+        //         }
+        //     }
+        // }
 
         stage('Stash / Unstash Demo (tool-free)') {
             steps {
